import { type Letter, Color } from "../types";
import { type Map } from "../types";

export const letterPool: Map<Array<Letter>> = {
    de: [
        { character: "A", color: Color.Green },
        { character: "B", color: Color.Grey },
        { character: "C", color: Color.Grey },
        { character: "D", color: Color.Grey },
        { character: "E", color: Color.Green },
        { character: "F", color: Color.Grey },
        { character: "G", color: Color.Grey },
        { character: "H", color: Color.Green },
        { character: "I", color: Color.Green },
        { character: "J", color: Color.Red },
        { character: "K", color: Color.Grey },
        { character: "L", color: Color.Grey },
        { character: "M", color: Color.Grey },
        { character: "N", color: Color.Green },
        { character: "O", color: Color.Grey },
        { character: "P", color: Color.Red },
        { character: "Q", color: Color.Red },
        { character: "R", color: Color.Green },
        { character: "S", color: Color.Green },
        { character: "T", color: Color.Green },
        { character: "U", color: Color.Grey },
        { character: "V", color: Color.Red },
        { character: "W", color: Color.Grey },
        { character: "X", color: Color.Red },
        { character: "Y", color: Color.Red },
        { character: "Z", color: Color.Grey },
        { character: "ß", color: Color.Red },
        { character: "Ä", color: Color.Red },
        { character: "Ö", color: Color.Red },
        { character: "Ü", color: Color.Red },
    ],
    en: [
        { character: "A", color: Color.Green },
        { character: "B", color: Color.Grey },
        { character: "C", color: Color.Grey },
        { character: "D", color: Color.Grey },
        { character: "E", color: Color.Green },
        { character: "F", color: Color.Grey },
        { character: "G", color: Color.Grey },
        { character: "H", color: Color.Grey },
        { character: "I", color: Color.Green },
        { character: "J", color: Color.Red },
        { character: "K", color: Color.Red },
        { character: "L", color: Color.Green },
        { character: "M", color: Color.Grey },
        { character: "N", color: Color.Green },
        { character: "O", color: Color.Green },
        { character: "P", color: Color.Grey },
        { character: "Q", color: Color.Red },
        { character: "R", color: Color.Green },
        { character: "S", color: Color.Green },
        { character: "T", color: Color.Green },
        { character: "U", color: Color.Grey },
        { character: "V", color: Color.Red },
        { character: "W", color: Color.Grey },
        { character: "X", color: Color.Red },
        { character: "Y", color: Color.Grey },
        { character: "Z", color: Color.Red },
    ],
    sv: [
        { character: "A", color: Color.Green },
        { character: "B", color: Color.Red },
        { character: "C", color: Color.Red },
        { character: "D", color: Color.Green },
        { character: "E", color: Color.Green },
        { character: "F", color: Color.Grey },
        { character: "G", color: Color.Grey },
        { character: "H", color: Color.Grey },
        { character: "I", color: Color.Green },
        { character: "J", color: Color.Red },
        { character: "K", color: Color.Grey },
        { character: "L", color: Color.Green },
        { character: "M", color: Color.Grey },
        { character: "N", color: Color.Green },
        { character: "O", color: Color.Grey },
        { character: "P", color: Color.Grey },
        { character: "Q", color: Color.Red },
        { character: "R", color: Color.Green },
        { character: "S", color: Color.Green },
        { character: "T", color: Color.Green },
        { character: "U", color: Color.Grey },
        { character: "V", color: Color.Grey },
        { character: "W", color: Color.Red },
        { character: "X", color: Color.Red },
        { character: "Y", color: Color.Grey },
        { character: "Z", color: Color.Red },
        { character: "Å", color: Color.Grey },
        { character: "Ä", color: Color.Grey },
        { character: "Ö", color: Color.Red },
    ]
};